[package]
name = "volex"
version = "0.1.0"
edition = "2024"

[features]
default = []
rpc = ["tokio"]

[dependencies]
tokio = { version = "1", features = ["net", "io-util", "sync", "rt", "macros"], optional = true }
